# Hide server signature (i.e. Apache version)
ServerSignature Off
ServerTokens Prod

<VirtualHost *:80>
    # Identify the correct IP address from Traefik reverse proxy
    RemoteIPHeader X-Real-IP
    RemoteIPInternalProxy 10.0.0.0/8
    RemoteIPInternalProxy 172.16.0.0/12
    RemoteIPInternalProxy 192.168.0.0/16

    DocumentRoot /app/public

    <Directory "/app/public">
        AllowOverride All
        Require all granted
    </Directory>

    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
