@extends('layouts.legal')

@section('content')
    <table width="520" cellspacing="0" cellpadding="0" align="center">
        <tbody><tr>
            <td>
                <br><br>	<br><br><b><u>Declaraţie privind protecţia datelor</u></b><br><br>Gameforge Productions GmbH, respectiv Gameforge 4D GmbH, ambele cu sediul în Albert-Nestler-Straße 8, 76131 Karlsruhe, precum şi celelalte companii ale grupului Gameforge ("Gameforge"), acordă importanţă maximă protecţiei datelor dumneavoastră personale. Următoarea declaraţie oferă informaţii cu privire la colectarea datelor personale şi modul în care acestea sunt procesate şi utilizate.<br><br><b>Obiectul acestei declaraţii privind protecţia datelor</b><br><br>
                Prezenta declaraţie privind protecţia datelor se aplică pentru toate serviciile oferite pe paginile de internet Gameforge, îndeosebi pe pagina de portal Gameforge, precum şi pe paginile individuale ale jocurilor online. Atât timp cât nu este menţionat altfel, această declaraţie privind protecţia datelor reglementează exclusiv modul în care Gameforge utilizează datele dumneavoastră personale. În cazul în care utilizaţi servicii ale unor terţe persoane, sunt valabile exclusiv condiţiile acestor terţe părţi privind protecţia datelor. Gameforge nu verifică condiţiile terţelor persoane privind protecţia datelor.<br><br><b>Instituţia responsabilă</b><br>Instituţia responsabilă în sensul legislaţiei germane federale privind protecţia datelor este Gameforge 4D GmbH, Albert-Nestler-Straße 8, 76131 Karlsruhe.<br>
                În caz de întrebări cu privire la protecţia datelor, vă rugăm să ne contactaţi la adresa datenschutz@gameforge.com. La această adresă puteţi formula în orice moment întrebări privind protecţia datelor, puteţi interoga, solicita modificarea sau ştergerea datelor dumneavoastră stocate de firma Gameforge. În mod alternativ, puteţi să vă adresaţi şi prin intermediul poştei, la adresa poştală de mai sus. În măsura în care este posibil, vă rugăm să indicaţi jocul online jucat de dumneavoastră, serverul şi numele dumneavoastră de jucător. Nu veţi avea de suportat alte costuri în afara celor de expediere, la tarifele de bază (aşadar costurile legăturilor dumneavoastră de internet, e-mail, telefonie mobilă sau fixă).<br><br><b>Generalităţi</b><br><br>
                Firma noastră colectează, procesează şi utilizează date cu caracter personal – atât timp cât nu este permis deja prin legislaţia în vigoare – doar cu acordul dumneavoastră. Dacă acordul este emis în format electronic, în cadrul ofertei noastre pe internet, acest lucru are loc conform obligaţiilor legale de informare.<br><br><b>Colectarea datelor pentru îndeplinirea contractului</b><br><br>
                În principiu, puteţi apela oferta noastră pe internet, fără să ne comunicaţi date cu caracter personal. Aveţi în orice moment posibilitatea de a decide dacă doriţi să ne comunicaţi datele dumneavoastră. Firma noastră colectează datele dumneavoastră pentru a putea îndeplini contractul de utilizare încheiat cu dumneavoastră. Printre acestea se numără, în afară de supravegherea respectării condiţiilor de utilizare şi a regulilor de joc, îndeosebi derularea corectă a ordinelor de plată iniţiate de dumneavoastră. Dacă vă înregistraţi pe paginile noastre de internet, participaţi la concursuri cu premii sau doriţi să vă abonaţi la newsletter-ul nostru, atunci indicarea datelor cu caracter personal este necesară. În cazul acestor date, este vorba, spre exemplu, de numele, adresa poştală, adresa de e-mail şi alte date personale, solicitate de Gameforge în situaţii individuale. În plus, pentru realizarea tehnică a ofertelor noastre, precum şi pentru supravegherea utilizării conform legii şi contractului a ofertelor noastre în cazul clienţilor înregistraţi, este necesară colectarea automată a altor date, ca de exemplu adresa IP. <br>
                Derularea corectă a raporturilor de utilizare include îndeosebi supravegherea respectării condiţiilor de utilizare şi a regulilor de joc. Dacă pentru participarea la jocurile noastre vă punem la dispoziţie clienţi pentru descărcare, atunci, în anumite împrejurări, în scopul prevenirii utilizărilor nepermise ale jocurilor şi al manipulărilor de date, împreună cu instalarea acestor clienţi poate fi instalat un program de evitare a intervenţiilor în joc în scopul modificării sau fraudării. <br>
                <br>
                Astfel de programe sunt lansate împreună cu jocul respectiv, exclusiv în ideea protejării datelor de client şi server din cadrul jocului respectiv. Pe durata participării la jocul respectiv poate avea loc o analiză a aplicaţiei software de client, a comunicaţiei tehnice a clientului şi a serverelor noastre, precum şi a manipulărilor tehnice şi mijloacelor auxiliare nepermise, cunoscute (îndeosebi hack-uri şi cheat-uri). Nu au loc analize suplimentare ale computerului şi datelor dumneavoastră. Îndeosebi nu se evaluează comunicarea internă a jocului sau date ce nu au legătură cu jocul de pe PC-ul dumneavoastră. Dacă pe computerul dumneavoastră nu se constată modificări ale clientului sau ale comunicării dintre client şi server, nu se colectează date cu caracter personal şi, mai ales, nu se trimit către serverele de jocuri respective sau către Gameforge. În cazul în care se constată utilizarea abuzivă, îndeosebi manipularea tehnică şi încălcarea condiţiilor de utilizare şi a regulilor de joc, se transmit către Gameforge datele necesare pentru combaterea utilizării abuzive. Dacă odată cu instalarea unui joc se instalează un astfel de program, dumneavoastră sunteţi informat în acest sens în mod expres, separat. Puteţi întrerupe oricând instalarea sau o puteţi anula, prin întreruperea instalării clientului, respectiv dezinstalarea clientului.<br><br><b>Cookie-uri</b><br><br>
                În scopuri tehnice sau pentru a vă face oferta noastră pe internet cât mai plăcută, firma noastră, ca multe alte companii, utilizează aşa-numite cookie-uri. De regulă, aceste cookie-uri sunt şterse automat de pe hard disk-ul dumneavoastră după încheierea vizitei dumneavoastră pe paginile noastre de web. Totuşi, unele cookie-uri pot fi stocate pe hard disk-ul dumneavoastră pe o perioadă mai îndelungată, din motive tehnice. Browserul dumneavoastră de internet poate fi configurat în aşa fel, încât cookie-urile să fie, în general, respinse sau să fie şterse, în situaţii individuale. <b>Dacă nu doriţi stocarea de cookie-uri sau doriţi să ştergeţi cookie-uri individuale, urmaţi instrucţiunile producătorului browserului dumneavoastră.</b> În acest caz, utilizarea paginilor noastre de internet poate fi restricţionată, complet sau parţial, din motive tehnice.<br><br><b>Colectarea datelor în scopuri statistice</b><br><br>
                În cadrul evaluărilor statistice, în domenii parţiale ale ofertelor noastre pe internet, colectăm date precum sistemul de operare şi versiunea, browserul şi versiunea, adresa IP, precum şi alte date ale sistemului. Aceste date sunt utilizate pentru evaluări statistice, îndeosebi în scopul unei mai bune adaptări a ofertelor noastre pe internet la necesităţile utilizatorilor. Pe cât posibil, datele sunt anonimizate. Acestea nu vor fi transmise către terţe persoane.<br><br><b>Revocarea acordurilor</b><br><br>
                Dacă procesarea datelor dumneavoastră cu caracter personal se bazează pe acordul dumneavoastră şi nu pe justificări contractuale sau legale, aveţi dreptul oricând să revocaţi acordul de procesare a datelor. <br>
                Dacă revocarea se referă la primirea de newsletttere sau alte mailuri, vă vom informa cu privire la posibilitatea dezabonării în cadrul notificărilor respective. Nu există alte costuri pentru dezabonare în afară de cele de transmitere, conform tarifelor de bază. <br>
                Pentru alte situaţii, pentru revocarea acordurilor dumneavoastră, vă rugăm să vă adresaţi serviciului de suport al paginii web utilizate, respectiv al jocului utilizat. Nu există alte costuri pentru revocare în afară de cele de transmitere, conform tarifelor de bază.<br><br><b>Utilizarea pseudonimelor</b><br><br>
                În multe cazuri, folosirea serviciilor de la Gameforge este posibilă prin utilizarea de pseudonime. Utilizatorii sunt încurajaţi să utilizeze această posibilitate.<br><br><b>Utilizarea datelor dumneavoastră</b><br>Datele dumneavoastră cu caracter personal sunt utilizate pentru crearea unei oferte adecvate a serviciilor şi îmbunătăţirea permanentă a acestora. Gameforge utilizează informaţiile dumneavoastră personale pentru motivarea, realizarea şi derularea raportului dvs. de utilizare cu Gameforge, precum şi pentru derularea plăţilor. În plus, utilizăm datele pentru a comunica cu dumneavoastră. Acest aspect include, după caz, informarea prin e-mail cu privire la noutăţi în oferta noastră de servicii. Astfel, utilizăm datele dumneavoastră pentru a vă informa în mod regulat cu privire la produse, servicii şi anumite evenimente din oferta noastră de servicii şi din oferta de servicii a grupului nostru de întreprinderi, ce ar putea prezenta interes pentru dumneavoastră. De asemenea există posibilitatea de a primi mailuri în cadrul sondajelor noastre printre clienţi. <br>
                Puteţi primi e-mail-uri de la noi, având următorul expeditor: <br>
                gameforge@news.gameforge.com, gameforge_web@news.gameforge.com, gameforge_mmo@news.gameforge.com<br>
                De asemenea, utilizăm datele dumneavoastră pentru a preveni utilizarea abuzivă a paginilor noastre web şi pentru a urmări accesuri neautorizate.<br><br><b>Transmiterea datelor</b><br><br>
                Se înţelege de la sine faptul că datele dumneavoastră cu caracter personal nu sunt vândute către terţe persoane. Gameforge transmite către terţe persoane datele personale primite de la dumneavoastră exclusiv în următoarele condiţii: colaborăm cu furnizori de servicii de plăţi (spre exemplu companii emitente de carduri de credit, bănci, PayPal, servicii de telefonie mobilă, instituţii colectoare de debite, etc.), furnizori şi realizatori de statistici, furnizori de servicii IT (de ex. centre de calcul, host-uri, servicii de baze de date). Aceşti furnizori au acces la datele dumneavoastră personale doar în măsura în care acest lucru este necesar la îndeplinirea sarcinilor acestora. Aceşti furnizori sunt obligaţi să manevreze datele dumneavoastră personale în conformitate cu această declaraţie privind protecţia datelor, precum şi în conformitate cu legislaţia relevantă privind protecţia datelor. În situaţia în care se vinde Gameforge, companii controlate de Gameforge, societăţi fiică individuale sau divizii ale companiei, atunci, de regulă, informaţiile dumneavoastră de client sunt transmise împreună cu divizia respectivă a companiei. Bineînţeles că datele dumneavoastră sunt în continuare supuse acestei declaraţii privind protecţia datelor şi legislaţiei relevante privind protecţia datelor.<br><br><b>Ştergerea datelor</b><br><br>
                Dacă datele dumneavoastră nu mai sunt necesare în scopurile menţionate anterior, inclusiv în vederea decontării, din motive fiscale sau orice alte motive legale, acestea vor fi şterse.<br><br><b>Siguranţa datelor</b><br><br>
                Firma noastră procesează informaţiile colectate de la dumneavoastră în conformitate cu legislaţia germană privind protecţia datelor. Toţi angajaţii sunt obligaţi şi instruiţi în acest sens să respecte confidenţialitatea datelor şi prevederile privind protecţia datelor. În cazul procedurilor de plată, datele dumneavoastră sunt transmise criptat, prin utilizarea procedeului SSL. Transferul nostru SSL este certificat THAWTE.<br><br>		</td>
        </tr>
        <tr>
            <td align="left">
                <br>
                <br>
                <b><u>Navigare:</u></b>
                <br>
                <br>
                &nbsp;-&nbsp;<a href="{{ url('legal/terms') }}">Termeni si Conditii Gameforge 4D GmbH</a>&nbsp;-&nbsp;<br/>
                &nbsp;-&nbsp;<a href="{{ url('legal/imprint') }}">Date contact Gameforge 4D GmbH</a>&nbsp;-&nbsp;<br/>
                &nbsp;-&nbsp;<a href="{{ url('legal/privacy') }}">Protectia Informatiilor Gameforge 4D GmbH</a>&nbsp;-&nbsp;<br/>
                <br>
                <br>
            </td>
        </tr>
        </tbody>
    </table>
@endsection
